#!/usr/bin/env python3
"""
Convert DOCX to Markdown using mammoth (no pandoc required).

Usage:
    python convert_docx_mammoth.py input.docx output.md
    python convert_docx_mammoth.py input.docx  # Auto-generate output name
    python convert_docx_mammoth.py input.docx --no-cleanup  # Skip format cleanup
"""

# 导入系统、正则表达式、Base64等标准库
# Import system, regular expression, Base64 and other standard libraries
import sys
import re
import base64
from pathlib import Path

# 导入第三方库 mammoth 用于文档转换
# Import third-party library mammoth for document conversion
import mammoth


class ImageHandler:
    """处理从 DOCX 文件中提取的图像，将其保存到本地目录中
    Handles image extraction from DOCX files by saving them to a local directory"""

    def __init__(self, md_path: Path):
        """初始化图像处理器
        Initialize image handler"""

        # 设置 Markdown 目录和图像子目录
        # Set Markdown directory and images subdirectory
        self.md_dir = md_path.parent
        self.images_dir = self.md_dir / "images"
        self.image_counter = 0

    def __call__(self, image):
        """处理单个图像对象并保存为物理文件
        Process a single image object and save as a physical file"""

        # 增加图像计数器并确保目录存在
        # Increment image counter and ensure directory exists
        self.image_counter += 1
        self.images_dir.mkdir(parents=True, exist_ok=True)

        # 从内容类型确定文件扩展名
        # Determine file extension from content type
        extension = image.content_type.split("/")[-1]
        if extension == "jpeg":
            extension = "jpg"

        # 生成图像文件名和物理路径
        # Generate image filename and physical path
        image_filename = f"{self.md_dir.name}_image_{self.image_counter}.{extension}"
        image_path = self.images_dir / image_filename

        # 将图像内容写入文件
        # Write image content to file
        with image.open() as image_bytes:
            image_path.write_bytes(image_bytes.read())

        # 返回 Markdown 链接所需的路径（相对于 MD 文件）
        # Return path for markdown link (relative to MD file)
        return {
            "src": f"images/{image_filename}"
        }


def cleanup_markdown(content: str) -> str:
    """清理 Mammoth 转换过程中出现的 Markdown 格式问题
    Clean up markdown formatting issues from mammoth conversion"""

    # 将 __text__ 替换为标准的 Markdown 加粗格式 **text**
    # Replace __text__ with proper markdown bold format **text**
    content = re.sub(r'__([^_]+)__', r'**\1**', content)

    # 移除 mammoth 生成的不必要的转义字符
    # Remove unnecessary escape characters generated by mammoth
    content = content.replace(r'\-', '-')
    content = content.replace(r'\.', '.')
    content = content.replace(r'\(', '(')
    content = content.replace(r'\)', ')')
    content = content.replace(r'\[', '[')
    content = content.replace(r'\]', ']')

    # 清理多余的空行（超过两个连续空行缩减为一个）
    # Clean up excess blank lines (reduce more than 2 consecutive to one)
    content = re.sub(r'\n{3,}', '\n\n', content)

    # 确保标题（#）周围有正确的间距
    # Ensure proper spacing around headings (#)
    lines = content.split('\n')
    cleaned_lines = []
    for i, line in enumerate(lines):
        # 如果是标题且前一行不是空行，则在上方补一个空行
        # If it's a heading and previous line isn't blank, add a blank line above
        if line.startswith('#') and i > 0 and cleaned_lines and cleaned_lines[-1].strip():
            cleaned_lines.append('')
        cleaned_lines.append(line)

    content = '\n'.join(cleaned_lines)

    # 移除每一行末尾的多余空格
    # Remove trailing whitespace from each line
    content = '\n'.join(line.rstrip() for line in content.split('\n'))

    # 确保文件以单个换行符结尾
    # Ensure file ends with a single newline
    content = content.rstrip() + '\n'

    return content


def convert_docx_to_md(docx_path: Path, md_path: Path = None, cleanup: bool = True):
    """使用 mammoth 将指定的 DOCX 文件转换为 Markdown 格式
    Convert specified DOCX file to Markdown using mammoth"""

    # 检查输入文件是否存在
    # Check if input file exists
    if not docx_path.exists():
        print(f"✗ File not found: {docx_path}")
        sys.exit(1)

    # 如果未提供输出路径，则自动生成（同名 .md）
    # If output path is not provided, auto-generate it (same name .md)
    if md_path is None:
        md_path = docx_path.with_suffix('.md')

    # 创建输出目录
    # Create output directory
    md_path.parent.mkdir(parents=True, exist_ok=True)

    # 打印转换信息
    # Print conversion information
    print(f"Converting: {docx_path.name}")
    print(f"Output: {md_path}")

    # 初始化图像处理器
    # Initialize image handler
    image_handler = ImageHandler(md_path)

    try:
        # 打开 DOCX 文件并进行转换
        # Open DOCX file and perform conversion
        with open(docx_path, 'rb') as docx_file:
            result = mammoth.convert_to_markdown(
                docx_file,
                convert_image=mammoth.images.img_element(image_handler)
            )
            content = result.value

            # 如果开启了清理选项，则应用格式清理
            # If cleanup option is enabled, apply format cleanup
            if cleanup:
                content = cleanup_markdown(content)
                print("  Format cleanup: enabled")

            # 将转换结果写入 Markdown 文件
            # Write conversion result to Markdown file
            md_path.write_text(content, encoding='utf-8')

        # 如果转换过程中有警告，打印非样式的警告信息
        # If there are warnings during conversion, print non-style warnings
        if result.messages:
            important_warnings = [
                msg for msg in result.messages
                if 'Unrecognised paragraph style' not in str(msg)
            ]
            if important_warnings:
                print("\nWarnings:")
                for message in important_warnings:
                    print(f"  - {message}")

        # 打印转换成功提示
        # Print success message
        print(f"\n✓ Conversion successful!")
        print(f"  Output: {md_path}")

        # 读取转换后的文件并显示预览摘要
        # Read converted file and show preview summary
        content = md_path.read_text(encoding='utf-8')
        lines = content.split('\n')
        print(f"  Lines: {len(lines)}")
        print(f"  Size: {len(content)} bytes")

    except Exception as e:
        # 处理并打印转换失败的错误信息
        # Handle and print conversion failure error message
        print(f"✗ Conversion failed: {e}")
        sys.exit(1)


def main():
    """主函数：解析命令行参数并执行文件转换
    Main function: parse CLI arguments and execute file conversion"""

    # 校验命令行参数数量
    # Validate CLI arguments count
    if len(sys.argv) < 2:
        print("Usage: python convert_docx_mammoth.py <input.docx> [output.md] [--no-cleanup]")
        print("Example: python convert_docx_mammoth.py Lab1_Template.docx")
        print("         python convert_docx_mammoth.py Lab1_Template.docx Lab1.md")
        print("         python convert_docx_mammoth.py Lab1_Template.docx --no-cleanup")
        sys.exit(1)

    # 提取输入路径和初始化转换参数
    # Extract input path and initialize conversion parameters
    docx_path = Path(sys.argv[1])
    md_path = None
    cleanup = True

    # 循环遍历额外的命令行选项
    # Loop through extra CLI options
    for arg in sys.argv[2:]:
        if arg == '--no-cleanup':
            cleanup = False
        elif not arg.startswith('--'):
            md_path = Path(arg)

    # 执行核心转换逻辑
    # Execute core conversion logic
    convert_docx_to_md(docx_path, md_path, cleanup)


# 程序入口点，运行主函数
# Program entry point, run main function
if __name__ == '__main__':
    main()
