// ═══════════════════════════════════════════════════════════
// 批量简单图解 — 统计/优化/深度学习/ML算法/正则/损失/评估/分布/基础数学/信息论补充/线代补充
// ═══════════════════════════════════════════════════════════

import { makeSimpleDiagram } from './SimpleDiagrams'

// ── 统计 ──
export const CovarianceDiagram = makeSimpleDiagram({ name: '协方差', color: '#9b59b6', latex: String.raw`\text{Cov}(X,Y) = E[(X-\mu_X)(Y-\mu_Y)]`, explain: ['两个变量一起变化的趋势','• 正: 同增同减','• 负: 一增一减','• 0: 不相关'], known: ['X=[1,2,3], Y=[2,4,5]','μ_X=2, μ_Y=3.67'], steps: ['① (1-2)(2-3.67)=1.67','② (2-2)(4-3.67)=0','③ (3-2)(5-3.67)=1.33'], conclusion: 'Cov = 1.0 (正相关)' })
export const ZScoreDiagram = makeSimpleDiagram({ name: 'Z-Score', color: '#4ea8de', latex: String.raw`z = \frac{x - \mu}{\sigma}`, explain: ['数据标准化到均值0方差1','• BatchNorm 的标量版','• 去量纲，可比较','• 预处理必备'], known: ['x=85, μ=70, σ=10','求 z'], steps: ['① 85 - 70 = 15','② 15 / 10 = 1.5'], conclusion: 'z = 1.5 (高于均值1.5个σ)' })

// ── 优化 ──
export const RMSPropDiagram = makeSimpleDiagram({ name: 'RMSProp', color: '#e67e22', latex: String.raw`r_t = \rho r_{t-1} + (1-\rho) g_t^2`, explain: ['梯度平方的指数移动平均','• 自适应调节每个参数步长','• 梯度大→步长小','• Adam 的前身之一'], known: ['ρ=0.9, g₁=4','r₀=0, 求 r₁'], steps: ['① r₁ = 0.9×0 + 0.1×16','② = 1.6','③ Δθ = -ε/√(1.6+δ) × 4'], conclusion: '步长自适应缩小' })
export const AdamDiagram = makeSimpleDiagram({ name: 'Adam', color: '#2ecc71', latex: String.raw`\theta_{t+1} = \theta_t - \frac{\eta}{\sqrt{\hat{v}_t}+\epsilon}\hat{m}_t`, explain: ['动量 + 自适应学习率','• m: 一阶矩(动量)','• v: 二阶矩(RMSProp)','• 偏差校正: m̂, v̂'], known: ['β₁=0.9, β₂=0.999','η=0.001, g₁=2'], steps: ['① m₁=0.1×2=0.2','② v₁=0.001×4=0.004','③ m̂₁=0.2/0.1=2, v̂₁=0.004/0.001=4'], conclusion: 'Δθ = -0.001/√4 × 2 = -0.001' })
export const XavierInitDiagram = makeSimpleDiagram({ name: 'Xavier 初始化', color: '#9b59b6', latex: String.raw`W \sim U\left(-\sqrt{\frac{6}{m+n}}, \sqrt{\frac{6}{m+n}}\right)`, explain: ['根据层宽自动设范围','• 保持前向/反向方差不变','• 防止梯度消失/爆炸','• Tanh/Sigmoid 适用'], known: ['输入 m=256, 输出 n=128','求初始化范围'], steps: ['① 6/(256+128)=0.01563','② √0.01563≈0.125'], conclusion: 'W ~ U(-0.125, 0.125)' })
export const BatchNormDiagram = makeSimpleDiagram({ name: '批量归一化', color: '#3498db', latex: String.raw`\hat{x}_i = \frac{x_i - \mu_B}{\sqrt{\sigma_B^2 + \epsilon}}`, explain: ['每层输出标准化后再缩放','• γ,β 可学习参数','• 加速收敛，允许大学习率','• 所有现代网络的标配'], known: ['batch x=[1,3,5]','μ=3, σ²=2.67, ε=1e-5'], steps: ['① x̂₁=(1-3)/√2.67=-1.22','② x̂₂=(3-3)/√2.67=0','③ y=γ·x̂+β (可学习)'], conclusion: '输出均值≈0, 方差≈1' })

// ── 深度学习 ──
export const Conv1dDiagram = makeSimpleDiagram({ name: '1D 卷积', color: '#e74c3c', latex: String.raw`(f*g)(t) = \sum_\tau f(\tau) g(t-\tau)`, explain: ['滑动核逐元素相乘求和','• 信号/时间序列处理','• 文本 CNN','• 共享权重,平移不变'], known: ['f=[1,2,3,4,5]','g=[1,0,-1] (边缘检测核)'], steps: ['① t=2: 1×1+2×0+3×(-1)=-2','② t=3: 2×1+3×0+4×(-1)=-2','③ t=4: 3×1+4×0+5×(-1)=-2'], conclusion: '输出=[-2,-2,-2] 检测变化' })
export const Conv2dDiagram = makeSimpleDiagram({ name: '2D 卷积', color: '#3498db', latex: String.raw`S(i,j) = \sum_m \sum_n I(i+m,j+n) K(m,n)`, explain: ['卷积核在图像上滑动','• 提取局部特征(边缘/纹理)','• CNN 的核心操作','• 共享权重→参数效率高'], known: ['I=3×3图像, K=2×2核','K=[[1,0],[0,-1]]'], steps: ['① 左上: 1×1+2×0+4×0+5×(-1)=-4','② 右上: 2×1+3×0+5×0+6×(-1)=-4','③ 滑动覆盖整个图像'], conclusion: '输出 = 特征图 (feature map)' })
export const MultiHeadAttnDiagram = makeSimpleDiagram({ name: 'Multi-Head Attention', color: '#e67e22', latex: String.raw`\text{MH}(Q,K,V) = \text{Concat}(\text{head}_1,...,\text{head}_h)W^O`, explain: ['多个注意力头并行','• 每个头捕捉不同子空间','• h=8 或 16 (典型值)','• 拼接后线性投影'], known: ['d_model=512, h=8','d_k = 512/8 = 64'], steps: ['① 每个头: Attn(QWᵢQ, KWᵢK, VWᵢV)','② 8个头独立计算','③ Concat → W^O 投影回 512维'], conclusion: '捕捉多种注意力模式' })
export const PosEncodingDiagram = makeSimpleDiagram({ name: '位置编码', color: '#f39c12', latex: String.raw`PE_{(pos,2i)} = \sin\left(\frac{pos}{10000^{2i/d}}\right)`, explain: ['用正余弦编码位置','• Transformer 没有位置感知','• 不同频率覆盖不同尺度','• 可外推到更长序列'], known: ['pos=3, d=4, i=0','求 PE(3,0) 和 PE(3,1)'], steps: ['① PE(3,0)=sin(3/1)=0.141','② PE(3,1)=cos(3/1)=-0.99','③ 每个位置一个唯一向量'], conclusion: '位置信息注入到嵌入中' })
export const ResidualDiagram = makeSimpleDiagram({ name: '残差连接', color: '#2ecc71', latex: String.raw`y = F(x) + x`, explain: ['输出 = 变换 + 原始输入','• 梯度直通(不衰减)','• 允许训练极深网络','• ResNet/Transformer 核心'], known: ['x=[1,2,3]','F(x)=[0.1,-0.2,0.3]'], steps: ['① y₁=0.1+1=1.1','② y₂=-0.2+2=1.8','③ y₃=0.3+3=3.3'], conclusion: '即使 F≈0，信息也能传递' })
export const DropoutDiagram = makeSimpleDiagram({ name: 'Dropout', color: '#e74c3c', latex: String.raw`\tilde{h}_i = m_i \cdot h_i, \; m_i \sim \text{Bernoulli}(p)`, explain: ['训练时随机丢弃神经元','• 防止过拟合','• 相当于集成学习','• 测试时不丢弃,但要缩放'], known: ['h=[1,2,3,4], p=0.5','随机 mask m=[1,0,1,0]'], steps: ['① h̃=[1×1, 2×0, 3×1, 4×0]','② = [1, 0, 3, 0]','③ 测试时 ×p: [0.5,1,1.5,2]'], conclusion: '每次不同子网络→鲁棒' })
export const LayerNormDiagram = makeSimpleDiagram({ name: 'LayerNorm', color: '#4ea8de', latex: String.raw`\hat{x}_i = \frac{x_i - \mu}{\sqrt{\sigma^2 + \epsilon}}`, explain: ['在特征维度上归一化','• 不依赖 batch 大小','• Transformer 标配','• 替代 BatchNorm (NLP)'], known: ['x=[1,3,5] (一个样本)','μ=3, σ²=2.67'], steps: ['① x̂₁=(1-3)/√2.67=-1.22','② x̂₂=(3-3)/√2.67=0','③ x̂₃=(5-3)/√2.67=1.22'], conclusion: '每个样本独立归一化' })

// ── 序列模型 ──
export const RNNDiagram = makeSimpleDiagram({ name: 'RNN', color: '#e74c3c', latex: String.raw`h_t = \tanh(W_h h_{t-1} + W_x x_t + b)`, explain: ['当前状态=f(上一步,当前输入)','• 共享权重跨时间步','• 可处理变长序列','• 梯度消失限制长序列'], known: ['x=[x₁,x₂,x₃]','h₀=0, 求 h₁→h₃'], steps: ['① h₁=tanh(Wh·0 + Wx·x₁)','② h₂=tanh(Wh·h₁ + Wx·x₂)','③ h₃=tanh(Wh·h₂ + Wx·x₃)'], conclusion: 'h₃ 包含所有历史信息' })
export const LSTMDiagram = makeSimpleDiagram({ name: 'LSTM', color: '#3498db', latex: String.raw`c_t = f_t \odot c_{t-1} + i_t \odot \tilde{c}_t`, explain: ['遗忘门+输入门+输出门','• 解决梯度消失问题','• 可记忆长距离依赖','• NLP/机器翻译经典'], known: ['遗忘门 f: 要忘多少','输入门 i: 要记多少','输出门 o: 要输出多少'], steps: ['① f=σ(Wf·[h,x]): 选择遗忘','② i·c̃: 新信息','③ c=f⊙c_old + i⊙c̃'], conclusion: '记忆细胞 c 跨时间传递' })
export const GRUDiagram = makeSimpleDiagram({ name: 'GRU', color: '#27ae60', latex: String.raw`h_t = (1-z_t) \odot h_{t-1} + z_t \odot \tilde{h}_t`, explain: ['LSTM 的简化版','• 更新门 z: 新旧比例','• 重置门 r: 历史权重','• 参数更少,训练更快'], known: ['z=0.3 (30%用新)','h_old=1, h̃=0.5'], steps: ['① (1-0.3)×1 = 0.7','② 0.3×0.5 = 0.15','③ h = 0.7+0.15'], conclusion: 'h = 0.85 (偏向保留旧)' })

// ── ML 算法 ──
export const LinearRegressionDiagram = makeSimpleDiagram({ name: '线性回归', color: '#3498db', latex: String.raw`\hat{y} = w^T x + b`, explain: ['加权求和+截距','• 最简单的模型','• 所有模型的基石','• 全连接层就是它'], known: ['x=[2,3], w=[0.5,1]','b=1, 求 ŷ'], steps: ['① 0.5×2=1','② 1×3=3','③ 1+3+1=5'], conclusion: 'ŷ = 5' })
export const LogisticRegressionDiagram = makeSimpleDiagram({ name: '逻辑回归', color: '#e74c3c', latex: String.raw`P(y=1|x) = \sigma(w^Tx+b)`, explain: ['线性→Sigmoid→概率','• 二分类标准模型','• 输出可解释为概率','• CTR预估/信用评分'], known: ['w=[1,2], b=-3, x=[1,1]','求 P(y=1)'], steps: ['① z=1×1+2×1-3=0','② σ(0)=1/(1+e⁰)','③ =1/2=0.5'], conclusion: 'P = 0.5 (边界上)' })
export const SVMHingeDiagram = makeSimpleDiagram({ name: 'SVM 合页损失', color: '#9b59b6', latex: String.raw`L = \sum \max(0, 1-y_i(w^Tx_i+b))`, explain: ['间隔 <1 就惩罚','• 最大化分类间隔','• 核方法→非线性','• max(0,...) 形如合页'], known: ['正例 w·x=0.8, y=1','负例 w·x=-1.2, y=-1'], steps: ['① max(0,1-0.8)=0.2','② max(0,1-1.2)=0','③ L=0.2+0'], conclusion: '正例距离不够→惩罚0.2' })
export const KernelRBFDiagram = makeSimpleDiagram({ name: 'RBF 核', color: '#e67e22', latex: String.raw`K(x,x') = \exp(-\|x-x'\|^2 / 2\sigma^2)`, explain: ['隐式映射到无穷维','• 近的点 K≈1','• 远的点 K≈0','• SVM 非线性分类核心'], known: ['x=0, x\'=1, σ=1','求 K(0,1)'], steps: ['① ‖0-1‖²=1','② -1/(2×1)=-0.5','③ e^(-0.5)≈0.607'], conclusion: 'K = 0.607 (相对近)' })
export const KMeansDiagram = makeSimpleDiagram({ name: 'K-Means', color: '#2ecc71', latex: String.raw`J = \sum_{k=1}^K \sum_{x_i \in C_k} \|x_i - \mu_k\|^2`, explain: ['最小化点到中心距离','• 交替: 分配→更新中心','• K 需预先指定','• 无监督聚类经典'], known: ['K=2, 点=[1,2,8,9]','初始 μ₁=1, μ₂=9'], steps: ['① 分配: {1,2}→C₁, {8,9}→C₂','② 更新: μ₁=1.5, μ₂=8.5','③ 再分配→收敛'], conclusion: 'C₁={1,2}, C₂={8,9}' })
export const PCADiagram = makeSimpleDiagram({ name: 'PCA', color: '#4ea8de', latex: String.raw`Z = XW, \; W = \text{top-}k \text{ eigvecs}`, explain: ['找方差最大的方向投影','• 降维保留最多信息','• 去相关性','• 基于协方差矩阵特征值'], known: ['2D数据→1D','协方差矩阵特征值 λ₁=5, λ₂=0.5'], steps: ['① 保留率=5/(5+0.5)=90.9%','② 取 λ₁ 对应的特征向量','③ Z = X·w₁ (投影)'], conclusion: '降到1D保留91%信息' })
export const NaiveBayesDiagram = makeSimpleDiagram({ name: '朴素贝叶斯', color: '#1abc9c', latex: String.raw`P(y|x) \propto P(y)\prod_i P(x_i|y)`, explain: ['假设特征条件独立','• 计算极快','• 文本分类经典','• 垃圾邮件过滤'], known: ['P(垃圾)=0.4','P("免费"|垃圾)=0.8','P("免费"|正常)=0.1'], steps: ['① P(垃圾)×0.8=0.32','② P(正常)×0.1=0.06','③ 归一: 0.32/(0.32+0.06)'], conclusion: 'P(垃圾|"免费")=84%' })
export const InfoGainDiagram = makeSimpleDiagram({ name: '信息增益', color: '#f39c12', latex: String.raw`IG = H(D) - \sum \frac{|D_v|}{|D|} H(D_v)`, explain: ['分裂前后熵的减少量','• 决策树选特征的标准','• IG越大→特征越有用','• ID3/C4.5 核心'], known: ['D: 5正5负, H(D)=1','按特征A分: D₁=4正1负, D₂=1正4负'], steps: ['① H(D₁)=0.72, H(D₂)=0.72','② 加权: 0.5×0.72+0.5×0.72=0.72','③ IG=1-0.72=0.28'], conclusion: 'IG = 0.28 bits' })
export const GiniDiagram = makeSimpleDiagram({ name: '基尼系数', color: '#8e44ad', latex: String.raw`\text{Gini}(D) = 1 - \sum p_k^2`, explain: ['节点不纯度度量','• 越小→越纯','• 纯节点 Gini=0','• CART 树使用'], known: ['节点: 70%类A, 30%类B','求 Gini'], steps: ['① p_A²=0.49','② p_B²=0.09','③ 1-(0.49+0.09)'], conclusion: 'Gini = 0.42' })

// ── 正则化 ──
export const L2RegDiagram = makeSimpleDiagram({ name: 'L2 正则化', color: '#3498db', latex: String.raw`L_{reg} = L + \lambda \sum w_i^2`, explain: ['惩罚大权重','• 权重衰减(weight decay)','• 让模型更平滑','• Ridge 回归'], known: ['L=2.0, λ=0.01','w=[3,4], 求 L_reg'], steps: ['① ‖w‖²=9+16=25','② λ×25=0.25','③ L_reg=2.0+0.25'], conclusion: 'L_reg = 2.25' })
export const L1RegDiagram = makeSimpleDiagram({ name: 'L1 正则化', color: '#27ae60', latex: String.raw`L_{reg} = L + \lambda \sum |w_i|`, explain: ['让不重要权重变0','• 自动特征选择','• LASSO 回归','• 稀疏模型'], known: ['L=2.0, λ=0.01','w=[3,-4,0.01]'], steps: ['① ‖w‖₁=3+4+0.01=7.01','② λ×7.01=0.0701','③ 小权重0.01趋向→0'], conclusion: 'L_reg = 2.07, 自动选特征' })
export const ElasticNetDiagram = makeSimpleDiagram({ name: 'Elastic Net', color: '#e67e22', latex: String.raw`L + \lambda_1\sum|w_i| + \lambda_2\sum w_i^2`, explain: ['L1+L2 的结合体','• 既稀疏又平滑','• 高维回归首选','• 相关特征分组选择'], known: ['λ₁=0.01, λ₂=0.01','w=[3,-4]'], steps: ['① L1: 0.01×7=0.07','② L2: 0.01×25=0.25','③ 总正则=0.32'], conclusion: '兼得 L1 稀疏 + L2 平滑' })

// ── 损失函数 ──
export const BCELossDiagram = makeSimpleDiagram({ name: '二元交叉熵', color: '#e74c3c', latex: String.raw`L = -\frac{1}{n}\sum[y\log\hat{y}+(1-y)\log(1-\hat{y})]`, explain: ['二分类标准损失','• y=1 时惩罚 -logŷ','• y=0 时惩罚 -log(1-ŷ)','• 逻辑回归/GAN 核心'], known: ['y=1, ŷ=0.9','求 L'], steps: ['① -[1×log(0.9)]','② = -(-0.105)','③ = 0.105'], conclusion: 'L = 0.105 (预测好→损失小)' })
export const FocalLossDiagram = makeSimpleDiagram({ name: 'Focal Loss', color: '#9b59b6', latex: String.raw`FL = -\alpha(1-p_t)^\gamma \log(p_t)`, explain: ['降低易分类样本权重','• 解决类别不平衡','• γ=2 时效果好','• RetinaNet 提出'], known: ['γ=2, 易分样本 p=0.9','难分样本 p=0.1'], steps: ['① 易: (1-0.9)²×log(0.9)=0.001','② 难: (1-0.1)²×log(0.1)=1.866','③ 难/易 = 1866×!'], conclusion: '聚焦于难分类样本' })
export const TripletLossDiagram = makeSimpleDiagram({ name: 'Triplet Loss', color: '#e67e22', latex: String.raw`L = \max(0, d(a,p)^2 - d(a,n)^2 + \alpha)`, explain: ['拉近正样本,推远负样本','• 人脸识别 FaceNet','• 度量学习核心','• α 是间隔余量'], known: ['d(a,p)=0.3, d(a,n)=0.8','α=0.2'], steps: ['① 0.09-0.64+0.2','② =-0.35','③ max(0,-0.35)=0'], conclusion: 'L=0 (间隔足够大)' })
export const ContrastiveLossDiagram = makeSimpleDiagram({ name: '对比损失', color: '#2ecc71', latex: String.raw`L = -\log\frac{\exp(\text{sim}(z_i,z_j)/\tau)}{\sum_k \exp(\text{sim}(z_i,z_k)/\tau)}`, explain: ['正样本对相似度最大化','• SimCLR / CLIP 核心','• τ 温度控制分布锐度','• 自监督学习'], known: ['正对 sim=0.9','负对 sim=0.1, τ=0.5'], steps: ['① 分子: exp(0.9/0.5)=6.05','② 分母: 6.05+exp(0.2)=7.27','③ -log(6.05/7.27)'], conclusion: 'L = 0.18 (对比拉近正对)' })
export const HuberLossDiagram = makeSimpleDiagram({ name: 'Huber Loss', color: '#f39c12', latex: String.raw`L_\delta = \begin{cases} \frac{1}{2}a^2 & |a|\leq\delta \\ \delta(|a|-\frac{\delta}{2}) & |a|>\delta \end{cases}`, explain: ['MSE 和 MAE 的折中','• 小误差用 MSE (平滑)','• 大误差用 MAE (鲁棒)','• 对异常值不敏感'], known: ['δ=1, a₁=0.5, a₂=3'], steps: ['① |0.5|≤1: 0.5²/2=0.125','② |3|>1: 1×(3-0.5)=2.5'], conclusion: '大误差不爆炸(vs MSE的9)' })
export const GANLossDiagram = makeSimpleDiagram({ name: 'GAN 损失', color: '#8e44ad', latex: String.raw`\min_G \max_D E[\log D(x)] + E[\log(1-D(G(z)))]`, explain: ['生成器vs判别器博弈','• D 想分辨真假','• G 想骗过 D','• 纳什均衡→逼真生成'], known: ['D(真图)=0.9','D(G(z))=0.3'], steps: ['① D: log(0.9)+log(0.7)=0.25','② G: 想让D(G(z))→1','③ 交替训练直到平衡'], conclusion: 'D(真)≈D(假)≈0.5' })
export const VAEELBODiagram = makeSimpleDiagram({ name: 'VAE ELBO', color: '#3498db', latex: String.raw`\mathcal{L} = E[\log p(x|z)] - D_{KL}(q(z|x)\|p(z))`, explain: ['重构质量-隐空间正则','• 第一项: 重构误差','• 第二项: 隐空间→标准高斯','• 两者平衡→好生成'], known: ['重构误差=2.5','KL散度=1.2'], steps: ['① ELBO = -2.5 - 1.2','② = -3.7','③ 最大化ELBO=最小化3.7'], conclusion: '重构+正则的平衡' })

// ── 评估指标 ──
export const AccuracyDiagram = makeSimpleDiagram({ name: '准确率', color: '#2ecc71', latex: String.raw`\text{Acc} = \frac{TP+TN}{TP+TN+FP+FN}`, explain: ['预测正确的比例','• 最直观的指标','• 类别不平衡时误导','• 需配合其他指标'], known: ['TP=80, TN=10','FP=5, FN=5'], steps: ['① 分子=80+10=90','② 分母=80+10+5+5=100'], conclusion: 'Acc = 90%' })
export const PrecisionDiagram = makeSimpleDiagram({ name: '精确率', color: '#3498db', latex: String.raw`\text{Precision} = \frac{TP}{TP+FP}`, explain: ['预测为正中真正为正','• "查准率"','• 垃圾邮件: 别误杀','• FP 代价高时重要'], known: ['TP=80, FP=5'], steps: ['① 分子=80','② 分母=80+5=85'], conclusion: 'Precision = 94.1%' })
export const RecallDiagram = makeSimpleDiagram({ name: '召回率', color: '#e67e22', latex: String.raw`\text{Recall} = \frac{TP}{TP+FN}`, explain: ['真正为正中被找出的','• "查全率"','• 医疗: 别漏诊','• FN 代价高时重要'], known: ['TP=80, FN=5'], steps: ['① 分子=80','② 分母=80+5=85'], conclusion: 'Recall = 94.1%' })
export const F1Diagram = makeSimpleDiagram({ name: 'F1 分数', color: '#e74c3c', latex: String.raw`F_1 = 2\cdot\frac{P \cdot R}{P + R}`, explain: ['精确率和召回率的调和均值','• 两者的平衡点','• F1=1 完美, F1=0 最差','• NLP 评估常用'], known: ['P=0.9, R=0.8'], steps: ['① 2×0.9×0.8=1.44','② 0.9+0.8=1.7','③ 1.44/1.7'], conclusion: 'F1 = 0.847' })
export const IoUDiagram = makeSimpleDiagram({ name: 'IoU', color: '#9b59b6', latex: String.raw`\text{IoU} = \frac{|A \cap B|}{|A \cup B|}`, explain: ['预测框和真实框重叠度','• 目标检测核心指标','• IoU>0.5 算检测成功','• mAP 基于 IoU 阈值'], known: ['A∩B=60像素','A=100, B=80'], steps: ['① A∪B=100+80-60=120','② IoU=60/120'], conclusion: 'IoU = 0.5 (刚好及格)' })
export const RSquaredDiagram = makeSimpleDiagram({ name: 'R² 决定系数', color: '#4ea8de', latex: String.raw`R^2 = 1 - \frac{\sum(y_i-\hat{y}_i)^2}{\sum(y_i-\bar{y})^2}`, explain: ['模型解释方差的比例','• R²=1 完美拟合','• R²=0 和均值一样差','• 回归模型评估标准'], known: ['SS_res=2, SS_tot=10'], steps: ['① 2/10=0.2','② 1-0.2=0.8'], conclusion: 'R² = 0.8 (解释80%方差)' })
export const BiasVarianceDiagram = makeSimpleDiagram({ name: '偏差-方差分解', color: '#f39c12', latex: String.raw`E[(y-\hat{f})^2] = \text{Bias}^2 + \text{Var} + \text{Noise}`, explain: ['误差的三个来源','• 偏差: 模型太简单','• 方差: 模型太复杂','• 噪声: 数据本身的随机'], known: ['线性模型 vs 10阶多项式','哪个偏差大? 哪个方差大?'], steps: ['① 线性: 偏差大,方差小','② 10阶: 偏差小,方差大','③ 最优=两者平衡'], conclusion: '简单↔复杂 的权衡' })

// ── 概率分布 ──
export const BernoulliDiagram = makeSimpleDiagram({ name: '伯努利分布', color: '#e74c3c', latex: String.raw`P(X=k) = p^k(1-p)^{1-k}`, explain: ['单次试验成功/失败','• k∈{0,1}','• Dropout 的概率模型','• 最简单的分布'], known: ['p=0.7 (成功概率)'], steps: ['① P(X=1)=0.7','② P(X=0)=0.3'], conclusion: '两点分布' })
export const BinomialDiagram = makeSimpleDiagram({ name: '二项分布', color: '#3498db', latex: String.raw`P(X=k) = \binom{n}{k}p^k(1-p)^{n-k}`, explain: ['n次独立试验中成功k次','• 伯努利的多次版','• 质量控制/假设检验','• n大时→正态分布'], known: ['n=10, p=0.5, k=7'], steps: ['① C(10,7)=120','② 0.5⁷×0.5³=0.5¹⁰','③ 120/1024=0.117'], conclusion: 'P = 11.7%' })
export const PoissonDiagram = makeSimpleDiagram({ name: '泊松分布', color: '#27ae60', latex: String.raw`P(X=k) = \frac{\lambda^k e^{-\lambda}}{k!}`, explain: ['单位时间事件次数','• λ = 平均发生率','• 稀有事件建模','• n大p小时二项→泊松'], known: ['λ=3 (平均3次/小时)','k=5'], steps: ['① 3⁵=243','② e⁻³=0.0498','③ 243×0.0498/120'], conclusion: 'P(5次) ≈ 10.1%' })
export const UniformDiagram = makeSimpleDiagram({ name: '均匀分布', color: '#f39c12', latex: String.raw`f(x) = \frac{1}{b-a}`, explain: ['区间内等概率','• 随机初始化','• 蒙特卡洛采样','• Xavier 初始化用'], known: ['a=0, b=10, x=3'], steps: ['① f(3)=1/(10-0)','② =0.1'], conclusion: 'P(任何子区间) 相同' })
export const ExponentialDiagram = makeSimpleDiagram({ name: '指数分布', color: '#e67e22', latex: String.raw`f(x) = \lambda e^{-\lambda x}`, explain: ['事件间隔时间','• 无记忆性','• 泊松过程间隔','• 生存分析基础'], known: ['λ=0.5 (半小时一次)','P(等待>2小时)?'], steps: ['① P(X>2)=e^(-0.5×2)','② =e⁻¹','③ ≈0.368'], conclusion: 'P = 36.8%' })
export const BetaDiagram = makeSimpleDiagram({ name: 'Beta 分布', color: '#9b59b6', latex: String.raw`f(x;\alpha,\beta) = \frac{x^{\alpha-1}(1-x)^{\beta-1}}{B(\alpha,\beta)}`, explain: ['概率的概率','• 贝叶斯先验','• A/B 测试','• α,β 控制形状'], known: ['α=2, β=5','(偏向小值)'], steps: ['① 均值=α/(α+β)=2/7≈0.29','② 众数=(α-1)/(α+β-2)=1/5=0.2'], conclusion: '峰值在0.2附近' })
export const CategoricalDiagram = makeSimpleDiagram({ name: '分类分布', color: '#1abc9c', latex: String.raw`P(X=k) = p_k, \sum p_k = 1`, explain: ['K类中选一类','• Softmax 输出','• 骰子模型','• 多分类基础'], known: ['K=3, p=[0.5,0.3,0.2]','投一次'], steps: ['① P(类1)=0.5','② P(类2)=0.3','③ P(类3)=0.2'], conclusion: '伯努利的多类推广' })

// ── 基础数学 ──
export const ExponentRulesDiagram = makeSimpleDiagram({ name: '指数法则', color: '#e74c3c', latex: String.raw`a^m \cdot a^n = a^{m+n}`, explain: ['指数运算基础规则','• 同底数相乘→指数相加','• 幂的幂→指数相乘','• 负指数→取倒数'], known: ['2³ × 2⁴ = ?'], steps: ['① 2³ × 2⁴ = 2^(3+4)','② = 2⁷ = 128'], conclusion: '指数相加: 2⁷ = 128' })
export const LogRulesDiagram = makeSimpleDiagram({ name: '对数法则', color: '#3498db', latex: String.raw`\log(ab) = \log a + \log b`, explain: ['对数把乘法变加法','• 交叉熵计算必备','• log(a/b)=loga-logb','• log(aⁿ)=n·loga'], known: ['log₂(8×4) = ?'], steps: ['① log₂8 + log₂4','② = 3 + 2 = 5','③ 验证: 2⁵=32=8×4 ✓'], conclusion: 'log₂32 = 5' })
export const ChangeOfBaseDiagram = makeSimpleDiagram({ name: '换底公式', color: '#27ae60', latex: String.raw`\log_a b = \frac{\ln b}{\ln a}`, explain: ['任意底互转','• bit↔nat转换','• log₂ vs ln','• 计算器只有ln和lg'], known: ['log₂10 = ?'], steps: ['① ln10/ln2','② 2.303/0.693','③ ≈ 3.322'], conclusion: 'log₂10 ≈ 3.32' })
export const ExpLogInverseDiagram = makeSimpleDiagram({ name: '指数对数互逆', color: '#f39c12', latex: String.raw`e^{\ln x} = x, \; \ln(e^x) = x`, explain: ['exp和log互为逆运算','• Softmax 用 exp','• 交叉熵用 log','• 两者配合使用'], known: ['e^(ln5) = ?','ln(e³) = ?'], steps: ['① e^(ln5) = 5','② ln(e³) = 3'], conclusion: '互逆关系' })
export const QuadraticDiagram = makeSimpleDiagram({ name: '求根公式', color: '#9b59b6', latex: String.raw`x = \frac{-b \pm \sqrt{b^2-4ac}}{2a}`, explain: ['ax²+bx+c=0 的通解','• Δ=b²-4ac 判别式','• Δ>0 两个实根','• Δ=0 重根, Δ<0 无实根'], known: ['x²-5x+6=0','a=1,b=-5,c=6'], steps: ['① Δ=25-24=1','② x=(5±1)/2','③ x₁=3, x₂=2'], conclusion: 'x=2 或 x=3' })
export const BinomialTheoremDiagram = makeSimpleDiagram({ name: '二项式定理', color: '#e67e22', latex: String.raw`(a+b)^n = \sum_{k=0}^n \binom{n}{k}a^{n-k}b^k`, explain: ['(a+b)ⁿ 展开','• Pascal三角系数','• Taylor展开基础','• 概率论常用'], known: ['(1+x)³ = ?'], steps: ['① C(3,0)1³ + C(3,1)1²x','② + C(3,2)1x² + C(3,3)x³','③ = 1+3x+3x²+x³'], conclusion: '(1+x)³ = 1+3x+3x²+x³' })
export const CombinationDiagram = makeSimpleDiagram({ name: '组合数', color: '#1abc9c', latex: String.raw`\binom{n}{k} = \frac{n!}{k!(n-k)!}`, explain: ['n中选k的方案数','• 无序选择','• 概率论基础','• 二项分布系数'], known: ['C(5,2) = ?'], steps: ['① 5!/(2!×3!)','② 120/(2×6)','③ = 10'], conclusion: 'C(5,2) = 10 种选法' })
export const FactorialDiagram = makeSimpleDiagram({ name: '阶乘', color: '#e74c3c', latex: String.raw`n! = n \times (n\!-\!1) \times \cdots \times 1`, explain: ['n个元素全排列数','• 0!=1 (约定)','• 组合数的基础','• 泊松分布分母'], known: ['5! = ?'], steps: ['① 5×4=20','② 20×3=60','③ 60×2×1=120'], conclusion: '5! = 120' })
export const ArithSeriesDiagram = makeSimpleDiagram({ name: '等差数列', color: '#4ea8de', latex: String.raw`S_n = \frac{n(a_1+a_n)}{2}`, explain: ['首尾相加×项数÷2','• 高斯7岁的故事','• 复杂度分析用','• 1+2+...+n'], known: ['1+2+...+100'], steps: ['① n=100, a₁=1, a₁₀₀=100','② 100×(1+100)/2','③ = 100×101/2'], conclusion: 'S = 5050' })
export const GeomSeriesDiagram = makeSimpleDiagram({ name: '等比数列', color: '#2ecc71', latex: String.raw`S_n = a_1 \frac{1-r^n}{1-r}`, explain: ['公比r的有限/无穷求和','• |r|<1 → 收敛','• 指数衰减模型','• 折扣因子(RL)'], known: ['a₁=1, r=0.5, n=∞'], steps: ['① S=1/(1-0.5)','② =1/0.5','③ =2'], conclusion: 'S∞ = 2 (收敛!)' })
export const TaylorDiagram = makeSimpleDiagram({ name: 'Taylor 展开', color: '#8e44ad', latex: String.raw`f(x) = \sum_{n=0}^\infty \frac{f^{(n)}(a)}{n!}(x-a)^n`, explain: ['用多项式近似任意函数','• 各阶导数决定系数','• a=0 时叫 Maclaurin','• Newton法/优化分析基础'], known: ['e^x 在 a=0 展开'], steps: ['① f(0)=1, f\'(0)=1, f\'\'(0)=1...','② eˣ=1+x+x²/2+x³/6+...','③ 取前几项近似'], conclusion: 'e^x ≈ 1+x+x²/2 (很准!)' })
export const EulerFormulaDiagram = makeSimpleDiagram({ name: 'Euler 公式', color: '#e74c3c', latex: String.raw`e^{i\theta} = \cos\theta + i\sin\theta`, explain: ['指数↔三角的桥梁','• θ=π → e^(iπ)+1=0','• 位置编码的数学基础','• 傅里叶变换核心'], known: ['θ=π/2'], steps: ['① cos(π/2)=0','② sin(π/2)=1','③ e^(iπ/2) = i'], conclusion: 'e^(iπ/2) = i' })
export const PythagoreanDiagram = makeSimpleDiagram({ name: '勾股定理', color: '#3498db', latex: String.raw`a^2 + b^2 = c^2`, explain: ['直角三角形三边关系','• 欧氏距离的本质','• L2范数的基础','• 所有距离度量的根'], known: ['a=3, b=4, 求 c'], steps: ['① 9+16=25','② √25=5'], conclusion: 'c = 5 (3-4-5三角形)' })
export const TrigBasicDiagram = makeSimpleDiagram({ name: '三角恒等式', color: '#27ae60', latex: String.raw`\sin^2\theta + \cos^2\theta = 1`, explain: ['单位圆基本性质','• 旋转矩阵用到','• 位置编码基础','• 正交性保证'], known: ['θ=30°'], steps: ['① sin²30=0.25','② cos²30=0.75','③ 0.25+0.75=1 ✓'], conclusion: '恒成立!' })
export const SumProductDiagram = makeSimpleDiagram({ name: '求和与连乘', color: '#f39c12', latex: String.raw`\sum_{i=1}^n a_i, \quad \prod_{i=1}^n a_i`, explain: ['Σ=加法, Π=乘法','• 损失函数用 Σ','• 似然函数用 Π','• log 把 Π 变 Σ'], known: ['a=[2,3,5]'], steps: ['① Σ=2+3+5=10','② Π=2×3×5=30','③ logΠ=log2+log3+log5'], conclusion: 'Σ=10, Π=30' })
export const AbsValueDiagram = makeSimpleDiagram({ name: '绝对值', color: '#e67e22', latex: String.raw`|x| = \begin{cases} x & x\geq0 \\ -x & x<0 \end{cases}`, explain: ['到原点的距离','• MAE 的基础','• L1范数的基础','• ReLU: max(0,x)'], known: ['|-3|=? |5|=?'], steps: ['① |-3|=3','② |5|=5'], conclusion: '去掉负号' })
export const FloorCeilDiagram = makeSimpleDiagram({ name: '取整', color: '#1abc9c', latex: String.raw`\lfloor x \rfloor, \; \lceil x \rceil`, explain: ['下取整/上取整','• 卷积输出尺寸计算','• 分组数计算','• 离散化'], known: ['x=3.7'], steps: ['① ⌊3.7⌋=3 (向下)','② ⌈3.7⌉=4 (向上)'], conclusion: '⌊⌋向下, ⌈⌉向上' })
export const MaxMinDiagram = makeSimpleDiagram({ name: 'max/min/argmax', color: '#4ea8de', latex: String.raw`\arg\max_i a_i = j \iff a_j \geq a_i`, explain: ['最大值的索引','• 分类预测取 argmax','• ReLU = max(0,x)','• 池化 = max pooling'], known: ['a=[1.2, 3.5, 2.8]'], steps: ['① max=3.5','② argmax=2 (第2个)'], conclusion: '预测类别=2' })
export const SetOpsDiagram = makeSimpleDiagram({ name: '集合运算', color: '#8e44ad', latex: String.raw`|A \cup B| = |A|+|B|-|A \cap B|`, explain: ['并交补,容斥原理','• IoU 的数学基础','• 概率论事件空间','• 集合论基本操作'], known: ['|A|=5, |B|=3, |A∩B|=2'], steps: ['① |A∪B|=5+3-2','② =6'], conclusion: '减去重复计数' })

// ── 信息论补充 ──
export const MutualInfoDiagram = makeSimpleDiagram({ name: '互信息', color: '#27ae60', latex: String.raw`I(X;Y) = \sum p(x,y)\log\frac{p(x,y)}{p(x)p(y)}`, explain: ['两变量共享多少信息','• I=0 → 独立','• 特征选择指标','• 互信息≥0 恒成立'], known: ['X,Y 完全相关'], steps: ['① p(x,y)=p(x)=p(y)','② log(1/p(x))=H(X)','③ I(X;Y)=H(X)'], conclusion: '完全相关: I = H' })
export const ConditionalEntropyDiagram = makeSimpleDiagram({ name: '条件熵', color: '#4ea8de', latex: String.raw`H(Y|X) = -\sum p(x,y)\log p(y|x)`, explain: ['已知X后Y的剩余不确定性','• H(Y|X)=0 → X完全决定Y','• H(Y|X)=H(Y) → X无用','• 决策树:选使H(Y|X)最小的X'], known: ['H(Y)=1, I(X;Y)=0.3'], steps: ['① H(Y|X)=H(Y)-I(X;Y)','② =1-0.3','③ =0.7'], conclusion: '还剩0.7 bits不确定' })
export const JointEntropyDiagram = makeSimpleDiagram({ name: '联合熵', color: '#f39c12', latex: String.raw`H(X,Y) = -\sum p(x,y)\log p(x,y)`, explain: ['X和Y同时的不确定性','• H(X,Y)≤H(X)+H(Y)','• 独立时取等号','• 互信息: I=H(X)+H(Y)-H(X,Y)'], known: ['H(X)=1, H(Y)=1','I(X;Y)=0.3'], steps: ['① H(X,Y)=H(X)+H(Y)-I','② =1+1-0.3','③ =1.7'], conclusion: 'H(X,Y) = 1.7 bits' })

// ── 线代补充 ──
export const TraceDiagram = makeSimpleDiagram({ name: '矩阵迹', color: '#e74c3c', latex: String.raw`\text{tr}(A) = \sum a_{ii} = \sum \lambda_i`, explain: ['对角线元素之和','• =特征值之和','• tr(AB)=tr(BA)','• Frobenius范数用到'], known: ['A=[[2,1],[3,4]]'], steps: ['① a₁₁=2, a₂₂=4','② tr=2+4=6'], conclusion: 'tr(A) = 6' })
export const FrobeniusDiagram = makeSimpleDiagram({ name: 'Frobenius 范数', color: '#3498db', latex: String.raw`\|A\|_F = \sqrt{\sum a_{ij}^2}`, explain: ['矩阵所有元素平方和开根','• 衡量矩阵"大小"','• 低秩近似误差度量','• =√tr(AᵀA)'], known: ['A=[[1,2],[3,4]]'], steps: ['① 1+4+9+16=30','② √30≈5.48'], conclusion: '‖A‖_F ≈ 5.48' })
export const HadamardDiagram = makeSimpleDiagram({ name: 'Hadamard 乘', color: '#27ae60', latex: String.raw`(A \odot B)_{ij} = a_{ij} \cdot b_{ij}`, explain: ['对应位置相乘','• LSTM门控核心','• Attention mask','• BatchNorm缩放'], known: ['A=[[1,2],[3,4]]','B=[[5,6],[7,8]]'], steps: ['① 1×5=5, 2×6=12','② 3×7=21, 4×8=32'], conclusion: 'A⊙B=[[5,12],[21,32]]' })
export const OuterProductDiagram = makeSimpleDiagram({ name: '外积', color: '#e67e22', latex: String.raw`\vec{u}\otimes\vec{v} = \vec{u}\vec{v}^T`, explain: ['列×行=矩阵','• 结果是秩1矩阵','• Attention权重更新','• 协方差矩阵表示'], known: ['u=[1,2], v=[3,4]'], steps: ['① [1]×[3,4]=[3,4]','② [2]×[3,4]=[6,8]'], conclusion: 'u⊗v=[[3,4],[6,8]]' })
export const PseudoInverseDiagram = makeSimpleDiagram({ name: '伪逆', color: '#9b59b6', latex: String.raw`A^+ = V\Sigma^+U^T`, explain: ['非方阵的"逆"','• 最小二乘解: x̂=A⁺b','• 基于SVD计算','• 超定/欠定通用'], known: ['A(m≠n), 求Ax=b'], steps: ['① SVD: A=UΣVᵀ','② Σ⁺: 非零值取倒数','③ x̂=VΣ⁺Uᵀb'], conclusion: '最小范数解' })
